export default [
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_VOTE_TIME_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'supportsInterface',
    inputs: [{ type: 'bytes4', name: '_interfaceId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'hasInitialized',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'newVote',
    inputs: [
      { type: 'bytes', name: '_executionScript' },
      { type: 'bytes', name: '_context' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'isVoteOpenForVoting',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'MAX_VOTES_DELEGATION_SET_LENGTH',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setAgreement',
    inputs: [{ type: 'address', name: '_agreement' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'getEVMScriptExecutor',
    inputs: [{ type: 'bytes', name: '_script' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'getRecoveryVault',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      { type: 'uint64', name: 'voteTime' },
      { type: 'uint64', name: 'supportRequiredPct' },
      { type: 'uint64', name: 'minAcceptQuorumPct' },
      { type: 'uint64', name: 'delegatedVotingPeriod' },
      { type: 'uint64', name: 'quietEndingPeriod' },
      { type: 'uint64', name: 'quietEndingExtension' },
      { type: 'uint64', name: 'executionDelay' },
    ],
    name: 'getSetting',
    inputs: [{ type: 'uint256', name: '_settingId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'settingsLength',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeQuietEndingConfiguration',
    inputs: [
      { type: 'uint64', name: '_quietEndingPeriod' },
      { type: 'uint64', name: '_quietEndingExtension' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_EXECUTION_DELAY_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'uint8', name: '' }],
    name: 'forwarderType',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'setRepresentative',
    inputs: [{ type: 'address', name: '_representative' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      { type: 'uint256', name: 'yea' },
      { type: 'uint256', name: 'nay' },
      { type: 'uint256', name: 'totalPower' },
      { type: 'uint64', name: 'startDate' },
      { type: 'uint64', name: 'snapshotBlock' },
      { type: 'uint8', name: 'status' },
      { type: 'uint256', name: 'settingId' },
      { type: 'uint256', name: 'actionId' },
      { type: 'uint64', name: 'pausedAt' },
      { type: 'uint64', name: 'pauseDuration' },
      { type: 'uint64', name: 'quietEndingExtensionDuration' },
      { type: 'uint8', name: 'quietEndingSnapshotSupport' },
      { type: 'bytes32', name: 'executionScriptHash' },
    ],
    name: 'getVote',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'forward',
    inputs: [
      { type: 'bytes', name: '_evmScript' },
      { type: 'bytes', name: '_context' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeMinAcceptQuorumPct',
    inputs: [{ type: 'uint64', name: '_minAcceptQuorumPct' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_SUPPORT_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canChallenge',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeExecutionDelay',
    inputs: [{ type: 'uint64', name: '_executionDelay' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'voteOnBehalfOf',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'bool', name: '_supports' },
      { type: 'address[]', name: '_voters' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canClose',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_DELEGATED_VOTING_PERIOD_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'onDisputableActionAllowed',
    inputs: [{ type: 'uint256', name: '_disputableActionId' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeSupportRequiredPct',
    inputs: [{ type: 'uint64', name: '_supportRequiredPct' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'allowRecoverability',
    inputs: [{ type: 'address', name: 'token' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'onDisputableActionChallenged',
    inputs: [
      { type: 'uint256', name: '_disputableActionId' },
      { type: 'uint256', name: '_challengeId' },
      { type: 'address', name: '_challenger' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'appId',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canVoteOnBehalfOf',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'address[]', name: '_voters' },
      { type: 'address', name: '_representative' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_QUIET_ENDING_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'getInitializationBlock',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHALLENGE_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'isRepresentativeOf',
    inputs: [
      { type: 'address', name: '_voter' },
      { type: 'address', name: '_representative' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'executeVote',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'bytes', name: '_executionScript' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CHANGE_QUORUM_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [
      { type: 'uint8', name: 'state' },
      { type: 'address', name: 'caster' },
    ],
    name: 'getCastVote',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'address', name: '_voter' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'transferToVault',
    inputs: [{ type: 'address', name: '_token' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canPerform',
    inputs: [
      { type: 'address', name: '_sender' },
      { type: 'bytes32', name: '_role' },
      { type: 'uint256[]', name: '_params' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'getEVMScriptRegistry',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canRepresentativesVote',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'initialize',
    inputs: [
      { type: 'address', name: '_token' },
      { type: 'uint64', name: '_voteTime' },
      { type: 'uint64', name: '_supportRequiredPct' },
      { type: 'uint64', name: '_minAcceptQuorumPct' },
      { type: 'uint64', name: '_delegatedVotingPeriod' },
      { type: 'uint64', name: '_quietEndingPeriod' },
      { type: 'uint64', name: '_quietEndingExtension' },
      { type: 'uint64', name: '_executionDelay' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'onDisputableActionVoided',
    inputs: [{ type: 'uint256', name: '_disputableActionId' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeDelegatedVotingPeriod',
    inputs: [{ type: 'uint64', name: '_delegatedVotingPeriod' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'getAgreement',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'CREATE_VOTES_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canForward',
    inputs: [
      { type: 'address', name: '_sender' },
      { type: 'bytes', name: '_evmScript' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'changeVoteTime',
    inputs: [{ type: 'uint64', name: '_voteTime' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'vote',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'bool', name: '_supports' },
    ],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canExecute',
    inputs: [{ type: 'uint256', name: '_voteId' }],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'canVote',
    inputs: [
      { type: 'uint256', name: '_voteId' },
      { type: 'address', name: '_voter' },
    ],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bytes32', name: '' }],
    name: 'SET_AGREEMENT_ROLE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'kernel',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'isPetrified',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'votesLength',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'nonpayable',
    payable: false,
    outputs: [],
    name: 'onDisputableActionRejected',
    inputs: [{ type: 'uint256', name: '_disputableActionId' }],
    constant: false,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'address', name: '' }],
    name: 'token',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'view',
    payable: false,
    outputs: [{ type: 'uint256', name: '' }],
    name: 'PCT_BASE',
    inputs: [],
    constant: true,
  },
  {
    type: 'function',
    stateMutability: 'pure',
    payable: false,
    outputs: [{ type: 'bool', name: '' }],
    name: 'isForwarder',
    inputs: [],
    constant: true,
  },
  {
    type: 'event',
    name: 'NewSetting',
    inputs: [{ type: 'uint256', name: 'settingId', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeVoteTime',
    inputs: [{ type: 'uint64', name: 'voteTime', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeSupportRequired',
    inputs: [{ type: 'uint64', name: 'supportRequiredPct', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeMinQuorum',
    inputs: [{ type: 'uint64', name: 'minAcceptQuorumPct', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeDelegatedVotingPeriod',
    inputs: [{ type: 'uint64', name: 'delegatedVotingPeriod', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeQuietEndingConfiguration',
    inputs: [
      { type: 'uint64', name: 'quietEndingPeriod', indexed: false },
      { type: 'uint64', name: 'quietEndingExtension', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeExecutionDelay',
    inputs: [{ type: 'uint64', name: 'executionDelay', indexed: false }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'StartVote',
    inputs: [
      { type: 'uint256', name: 'voteId', indexed: true },
      { type: 'address', name: 'creator', indexed: true },
      { type: 'bytes', name: 'context', indexed: false },
      { type: 'bytes', name: 'executionScript', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'PauseVote',
    inputs: [
      { type: 'uint256', name: 'voteId', indexed: true },
      { type: 'uint256', name: 'challengeId', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ResumeVote',
    inputs: [{ type: 'uint256', name: 'voteId', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CancelVote',
    inputs: [{ type: 'uint256', name: 'voteId', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ExecuteVote',
    inputs: [{ type: 'uint256', name: 'voteId', indexed: true }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'QuietEndingExtendVote',
    inputs: [
      { type: 'uint256', name: 'voteId', indexed: true },
      { type: 'bool', name: 'passing', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'CastVote',
    inputs: [
      { type: 'uint256', name: 'voteId', indexed: true },
      { type: 'address', name: 'voter', indexed: true },
      { type: 'bool', name: 'supports', indexed: false },
      { type: 'address', name: 'caster', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ChangeRepresentative',
    inputs: [
      { type: 'address', name: 'voter', indexed: true },
      { type: 'address', name: 'representative', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ProxyVoteFailure',
    inputs: [
      { type: 'uint256', name: 'voteId', indexed: true },
      { type: 'address', name: 'voter', indexed: true },
      { type: 'address', name: 'representative', indexed: true },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'ScriptResult',
    inputs: [
      { type: 'address', name: 'executor', indexed: true },
      { type: 'bytes', name: 'script', indexed: false },
      { type: 'bytes', name: 'input', indexed: false },
      { type: 'bytes', name: 'returnData', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RecoverToVault',
    inputs: [
      { type: 'address', name: 'vault', indexed: true },
      { type: 'address', name: 'token', indexed: true },
      { type: 'uint256', name: 'amount', indexed: false },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'AgreementSet',
    inputs: [{ type: 'address', name: 'agreement', indexed: true }],
    anonymous: false,
  },
]
